package com.frostfitness.app

import android.net.Uri
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.compose.setContent
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import java.time.LocalDate

private val Accent=Color(0xFF9BE52A);private val Canvas=Color(0xFFF2F2F7);private val Surface=Color.White;private val Ink=Color(0xFF111111);private val Secondary=Color(0xFF6E6E73);private val Line=Color(0xFFE5E5EA)
class Profile{var name by mutableStateOf("");var city by mutableStateOf("");var about by mutableStateOf("");var occupation by mutableStateOf("");var avatar by mutableStateOf("");var goal by mutableStateOf("");var age by mutableStateOf("");var height by mutableStateOf("");var weight by mutableStateOf("");var experience by mutableStateOf("");var days by mutableIntStateOf(3);var place by mutableStateOf("Зал");var health by mutableStateOf("")}
data class Measurement(val date:String,val values:Map<String,String>);data class ProgressPhotos(val date:String,val front:String,val side:String,val back:String)
enum class Screen{WELCOME,GOAL,BASICS,EXP,DAYS,PLACE,HEALTH,HOME,PROFILE}
class MainActivity:ComponentActivity(){override fun onCreate(b:Bundle?){super.onCreate(b);setContent{App()}}}
@Composable fun App(){val c=LocalContext.current;val p=remember{loadProfile(c)};var s by remember{mutableStateOf(loadScreen(c))};var ms by remember{mutableStateOf(loadMeasurements(c))};var ph by remember{mutableStateOf(loadPhotos(c))};LaunchedEffect(s,p.name,p.city,p.about,p.occupation,p.avatar,p.goal,p.age,p.height,p.weight,p.experience,p.days,p.place,p.health,ms,ph){save(c,p,s,ms,ph)};MaterialTheme(colorScheme=lightColorScheme(primary=Ink,background=Canvas,surface=Surface,onPrimary=Color.White,onBackground=Ink,onSurface=Ink)){androidx.compose.material3.Surface(Modifier.fillMaxSize(),color=Canvas){when(s){Screen.WELCOME->Page("Frost Fitness","Тренировки, питание и прогресс — в одном месте."){Hero("FF","Твой персональный фитнес-план вместе с Фростиком.");Primary("Настроить программу"){s=Screen.GOAL}};Screen.GOAL->Choice("Какая у тебя цель?",listOf("Снизить вес","Набрать мышцы","Стать сильнее","Поддерживать форму"),p.goal,{p.goal=it}){s=Screen.BASICS};Screen.BASICS->Page("О тебе","Эти данные нужны для персональной программы."){FieldNum("Возраст",p.age){p.age=it};FieldNum("Рост, см",p.height){p.height=it};FieldNum("Вес, кг",p.weight,true){p.weight=it};Primary(enabled=p.age.isNotBlank()&&p.height.isNotBlank()&&p.weight.isNotBlank()){s=Screen.EXP}};Screen.EXP->Choice("Опыт тренировок",listOf("Начинающий","До 1 года","1–3 года","Более 3 лет"),p.experience,{p.experience=it}){s=Screen.DAYS};Screen.DAYS->Page("Ритм тренировок","Сколько раз в неделю тебе удобно заниматься?"){Segment((2..5).map{it.toString()},p.days.toString()){p.days=it.toInt()};Primary(){s=Screen.PLACE}};Screen.PLACE->Choice("Где тренируемся?",listOf("Зал","Дом: гантели","Дом: без оборудования"),p.place,{p.place=it}){s=Screen.HEALTH};Screen.HEALTH->Page("Здоровье","Укажи ограничения, которые важно учитывать."){Field("Ограничения и противопоказания",p.health,4){p.health=it};Primary("Создать программу",p.health.isNotBlank()){s=Screen.HOME}};Screen.HOME->Home(p){s=Screen.PROFILE};Screen.PROFILE->ProfilePage(p,ms,{ms=ms+it},ph,{ph=ph+it}){s=Screen.HOME}}}}}
@Composable fun Home(p:Profile,profile:()->Unit){Page(if(p.name.isBlank())"Сегодня" else "Привет, ${p.name}","${p.goal} · ${p.days} тренировки в неделю"){Hero("Ф","Фростик рядом. Сегодня двигаемся по твоему плану.");CardBlock{Text("Сегодня",fontSize=13.sp,color=Secondary);Text("Тренировка всего тела",fontSize=22.sp,fontWeight=FontWeight.Bold);Text("45 мин · 6 упражнений",color=Secondary);Spacer(Modifier.height(10.dp));Primary("Начать тренировку"){} };Text("Твой прогресс",fontSize=22.sp,fontWeight=FontWeight.Bold);Row(horizontalArrangement=Arrangement.spacedBy(10.dp)){Stat("0","тренировок",Modifier.weight(1f));Stat(p.weight.ifBlank{"—"},"кг",Modifier.weight(1f))};SecondaryButton("Мой профиль и замеры",profile)}}
@Composable fun ProfilePage(p:Profile,ms:List<Measurement>,addM:(Measurement)->Unit,ph:List<ProgressPhotos>,addP:(ProgressPhotos)->Unit,back:()->Unit){var tab by remember{mutableIntStateOf(0)};Page("Профиль",p.name.ifBlank{"Персональные данные и прогресс"}){val tabs=listOf("Профиль","Замеры","Фото");Segment(tabs,tabs[tab]){tab=tabs.indexOf(it)};when(tab){0->ProfileFields(p);1->Measurements(ms,addM);2->PhotoProgress(ph,addP)};SecondaryButton("Готово",back)}}
@Composable fun ProfileFields(p:Profile){val c=LocalContext.current;val pick=rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()){u:Uri?->u?.let{runCatching{c.contentResolver.takePersistableUriPermission(it,android.content.Intent.FLAG_GRANT_READ_URI_PERMISSION)};p.avatar=it.toString()}};Column(horizontalAlignment=Alignment.CenterHorizontally,modifier=Modifier.fillMaxWidth()){Box(Modifier.size(104.dp).clip(CircleShape).background(Color(0xFFE9E9ED)),contentAlignment=Alignment.Center){Text(if(p.avatar.isBlank())"Ф" else "✓",fontSize=34.sp,fontWeight=FontWeight.Bold)};TextButton({pick.launch(arrayOf("image/*"))}){Text(if(p.avatar.isBlank())"Добавить фото" else "Изменить фото")}};Section("Основное"){Field("Имя",p.name){p.name=it};Field("Город",p.city){p.city=it};Field("Род деятельности",p.occupation){p.occupation=it};Field("О себе",p.about,4){p.about=it}};Section("Физические данные"){FieldNum("Возраст",p.age){p.age=it};FieldNum("Рост, см",p.height){p.height=it};FieldNum("Вес, кг",p.weight,true){p.weight=it}};Section("Тренировки"){Field("Стаж",p.experience){p.experience=it};Field("Цель",p.goal){p.goal=it};Field("Место тренировок",p.place){p.place=it};Field("Ограничения здоровья",p.health,3){p.health=it}};Text("Все изменения сохраняются автоматически.",color=Secondary,fontSize=13.sp)}
@Composable fun Measurements(items:List<Measurement>,add:(Measurement)->Unit){val labels=listOf("Вес","Шея","Плечи","Грудь","Талия","Живот","Бёдра","Бицепс левый","Бицепс правый","Предплечье левое","Предплечье правое","Бедро левое","Бедро правое","Икра левая","Икра правая");val v=remember{mutableStateMapOf<String,String>()};Section("Новый замер"){labels.forEach{l->FieldNum(if(l=="Вес")"$l, кг" else "$l, см",v[l]?:"",true){v[l]=it}}};Primary("Сохранить замер",v.values.any{it.isNotBlank()}){add(Measurement(LocalDate.now().toString(),v.toMap()));v.clear()};if(items.isNotEmpty()){Text("История",fontSize=22.sp,fontWeight=FontWeight.Bold);items.asReversed().forEach{m->CardBlock{Text(m.date,fontWeight=FontWeight.SemiBold);Text(m.values.filterValues{it.isNotBlank()}.entries.joinToString(" · "){"${it.key} ${it.value}"},color=Secondary)}}}}
@Composable fun PhotoProgress(items:List<ProgressPhotos>,add:(ProgressPhotos)->Unit){val c=LocalContext.current;var front by remember{mutableStateOf("")};var side by remember{mutableStateOf("")};var back by remember{mutableStateOf("")};fun keep(u:Uri?):String{if(u==null)return "";runCatching{c.contentResolver.takePersistableUriPermission(u,android.content.Intent.FLAG_GRANT_READ_URI_PERMISSION)};return u.toString()};val f=rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()){front=keep(it)};val s=rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()){side=keep(it)};val b=rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()){back=keep(it)};Hero("AI","Снимай прогресс в одинаковом свете и с одного расстояния. Позже ИИ сможет сравнивать изменения.");Section("Новая серия"){PhotoRow("Спереди",front.isNotBlank()){f.launch(arrayOf("image/*"))};PhotoRow("Сбоку",side.isNotBlank()){s.launch(arrayOf("image/*"))};PhotoRow("Сзади",back.isNotBlank()){b.launch(arrayOf("image/*"))}};Primary("Сохранить серию",front.isNotBlank()||side.isNotBlank()||back.isNotBlank()){add(ProgressPhotos(LocalDate.now().toString(),front,side,back));front="";side="";back=""};if(items.isNotEmpty()){Text("История фото",fontSize=22.sp,fontWeight=FontWeight.Bold);items.asReversed().forEach{CardBlock{Text(it.date,fontWeight=FontWeight.SemiBold);Text("Спереди ${if(it.front.isBlank())"—" else "✓"}   Сбоку ${if(it.side.isBlank())"—" else "✓"}   Сзади ${if(it.back.isBlank())"—" else "✓"}",color=Secondary)}}}}
@Composable fun Page(title:String,sub:String="",body:@Composable ColumnScope.()->Unit){Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).statusBarsPadding().navigationBarsPadding().padding(horizontal=20.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){Spacer(Modifier.height(12.dp));Text("FROST FITNESS",fontSize=12.sp,fontWeight=FontWeight.Bold,color=Secondary);Text(title,fontSize=34.sp,fontWeight=FontWeight.Bold,letterSpacing=(-1).sp);if(sub.isNotBlank())Text(sub,color=Secondary,fontSize=16.sp);Spacer(Modifier.height(2.dp));body();Spacer(Modifier.height(28.dp))}}
@Composable fun Hero(mark:String,text:String){Row(Modifier.fillMaxWidth().background(Surface,RoundedCornerShape(24.dp)).padding(18.dp),verticalAlignment=Alignment.CenterVertically,horizontalArrangement=Arrangement.spacedBy(14.dp)){Box(Modifier.size(52.dp).clip(CircleShape).background(Accent),contentAlignment=Alignment.Center){Text(mark,fontWeight=FontWeight.Bold,fontSize=20.sp)};Text(text,Modifier.weight(1f),fontSize=17.sp,fontWeight=FontWeight.SemiBold)}}
@Composable fun CardBlock(body:@Composable ColumnScope.()->Unit){Column(Modifier.fillMaxWidth().background(Surface,RoundedCornerShape(22.dp)).padding(18.dp),verticalArrangement=Arrangement.spacedBy(6.dp),content=body)}
@Composable fun Section(title:String,body:@Composable ColumnScope.()->Unit){Text(title.uppercase(),fontSize=12.sp,fontWeight=FontWeight.SemiBold,color=Secondary,modifier=Modifier.padding(start=4.dp,top=8.dp));Column(Modifier.fillMaxWidth().background(Surface,RoundedCornerShape(18.dp)).padding(horizontal=14.dp,vertical=4.dp),verticalArrangement=Arrangement.spacedBy(2.dp),content=body)}
@Composable fun Primary(text:String="Продолжить",enabled:Boolean=true,click:()->Unit){Button(click,Modifier.fillMaxWidth().height(54.dp),enabled=enabled,shape=RoundedCornerShape(16.dp),colors=ButtonDefaults.buttonColors(containerColor=Ink,contentColor=Color.White,disabledContainerColor=Line)){Text(text,fontWeight=FontWeight.SemiBold,fontSize=16.sp)}}
@Composable fun SecondaryButton(text:String,click:()->Unit){OutlinedButton(click,Modifier.fillMaxWidth().height(52.dp),shape=RoundedCornerShape(16.dp),colors=ButtonDefaults.outlinedButtonColors(contentColor=Ink)){Text(text,fontWeight=FontWeight.SemiBold)}}
@Composable fun Field(label:String,value:String,lines:Int=1,set:(String)->Unit){OutlinedTextField(value,set,label={Text(label)},singleLine=lines==1,minLines=lines,shape=RoundedCornerShape(14.dp),colors=OutlinedTextFieldDefaults.colors(unfocusedBorderColor=Line,focusedBorderColor=Ink,unfocusedContainerColor=Surface,focusedContainerColor=Surface),modifier=Modifier.fillMaxWidth().padding(vertical=3.dp))}
@Composable fun FieldNum(label:String,value:String,decimal:Boolean=false,set:(String)->Unit){OutlinedTextField(value,{raw->val x=raw.replace(',','.');set(if(decimal)x.filterIndexed{i,ch->ch.isDigit()||(ch=='.'&&i>0&&x.take(i).none{it=='.'})}else x.filter{it.isDigit()})},label={Text(label)},singleLine=true,shape=RoundedCornerShape(14.dp),keyboardOptions=KeyboardOptions(keyboardType=if(decimal)KeyboardType.Decimal else KeyboardType.Number),colors=OutlinedTextFieldDefaults.colors(unfocusedBorderColor=Line,focusedBorderColor=Ink,unfocusedContainerColor=Surface,focusedContainerColor=Surface),modifier=Modifier.fillMaxWidth().padding(vertical=3.dp))}
@Composable fun Segment(items:List<String>,selected:String,set:(String)->Unit){Row(Modifier.fillMaxWidth().background(Color(0xFFE3E3E8),RoundedCornerShape(12.dp)).padding(3.dp),horizontalArrangement=Arrangement.spacedBy(3.dp)){items.forEach{item->Button({set(item)},Modifier.weight(1f).height(38.dp),shape=RoundedCornerShape(10.dp),contentPadding=PaddingValues(horizontal=4.dp),colors=ButtonDefaults.buttonColors(containerColor=if(item==selected)Surface else Color.Transparent,contentColor=Ink),elevation=ButtonDefaults.buttonElevation(defaultElevation=if(item==selected)1.dp else 0.dp)){Text(item,fontSize=12.sp,fontWeight=if(item==selected)FontWeight.SemiBold else FontWeight.Normal)}}}}
@Composable fun Choice(title:String,items:List<String>,initial:String,set:(String)->Unit,next:()->Unit){var v by remember(title){mutableStateOf(initial)};Page(title,"Выбери один вариант"){items.forEach{item->Button({v=item;set(item)},Modifier.fillMaxWidth().height(58.dp),shape=RoundedCornerShape(16.dp),colors=ButtonDefaults.buttonColors(containerColor=Surface,contentColor=Ink)){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Text(item,Modifier.weight(1f),fontSize=16.sp);Text(if(v==item)"✓" else "",color=Color(0xFF34C759),fontWeight=FontWeight.Bold)}}};Primary(enabled=v.isNotBlank(),click=next)}}
@Composable fun Stat(value:String,label:String,m:Modifier=Modifier){Column(m.background(Surface,RoundedCornerShape(20.dp)).padding(16.dp)){Text(value,fontSize=28.sp,fontWeight=FontWeight.Bold);Text(label,color=Secondary,fontSize=13.sp)}}
@Composable fun PhotoRow(label:String,done:Boolean,click:()->Unit){Row(Modifier.fillMaxWidth().padding(vertical=8.dp),verticalAlignment=Alignment.CenterVertically){Text(label,Modifier.weight(1f),fontSize=16.sp);TextButton(click){Text(if(done)"Выбрано ✓" else "Выбрать")}}}
fun prefs(c:android.content.Context)=c.getSharedPreferences("frost_fitness",android.content.Context.MODE_PRIVATE)
fun loadProfile(c:android.content.Context)=Profile().apply{val x=prefs(c);name=x.getString("name","")!!;city=x.getString("city","")!!;about=x.getString("about","")!!;occupation=x.getString("occupation","")!!;avatar=x.getString("avatar","")!!;goal=x.getString("goal","")!!;age=x.getString("age","")!!;height=x.getString("height","")!!;weight=x.getString("weight","")!!;experience=x.getString("experience","")!!;days=x.getInt("days",3);place=x.getString("place","Зал")!!;health=x.getString("health","")!!}
fun loadScreen(c:android.content.Context)=runCatching{Screen.valueOf(prefs(c).getString("screen","WELCOME")!!)}.getOrDefault(Screen.WELCOME)
fun esc(s:String)=android.util.Base64.encodeToString(s.toByteArray(),android.util.Base64.NO_WRAP);fun unesc(s:String)=runCatching{String(android.util.Base64.decode(s,android.util.Base64.NO_WRAP))}.getOrDefault("")
fun save(c:android.content.Context,p:Profile,s:Screen,m:List<Measurement>,ph:List<ProgressPhotos>){prefs(c).edit().putString("name",p.name).putString("city",p.city).putString("about",p.about).putString("occupation",p.occupation).putString("avatar",p.avatar).putString("goal",p.goal).putString("age",p.age).putString("height",p.height).putString("weight",p.weight).putString("experience",p.experience).putInt("days",p.days).putString("place",p.place).putString("health",p.health).putString("screen",s.name).putString("measurements",m.joinToString(";"){esc(it.date)+","+esc(it.values.entries.joinToString("|"){e->e.key+"="+e.value})}).putString("photos",ph.joinToString(";"){listOf(it.date,it.front,it.side,it.back).joinToString(","){v->esc(v)}}).apply()}
fun loadMeasurements(c:android.content.Context):List<Measurement>{val raw=prefs(c).getString("measurements","")?:"";if(raw.isBlank())return emptyList();return raw.split(';').mapNotNull{r->val q=r.split(',',limit=2);if(q.size<2)null else Measurement(unesc(q[0]),unesc(q[1]).split('|').mapNotNull{e->val z=e.split('=',limit=2);if(z.size==2)z[0] to z[1] else null}.toMap())}}
fun loadPhotos(c:android.content.Context):List<ProgressPhotos>{val raw=prefs(c).getString("photos","")?:"";if(raw.isBlank())return emptyList();return raw.split(';').mapNotNull{r->val q=r.split(',');if(q.size==4)ProgressPhotos(unesc(q[0]),unesc(q[1]),unesc(q[2]),unesc(q[3]))else null}}