package com.frostfitness.app

import android.net.Uri
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.compose.setContent
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import java.time.LocalDate

private val Lime=androidx.compose.ui.graphics.Color(0xFFB7FF32);private val Bg=androidx.compose.ui.graphics.Color(0xFF090B0A);private val Card=androidx.compose.ui.graphics.Color(0xFF151816);private val Muted=androidx.compose.ui.graphics.Color(0xFFA8AEA9)
class Profile{var name by mutableStateOf("");var city by mutableStateOf("");var about by mutableStateOf("");var occupation by mutableStateOf("");var avatar by mutableStateOf("");var goal by mutableStateOf("");var age by mutableStateOf("");var height by mutableStateOf("");var weight by mutableStateOf("");var experience by mutableStateOf("");var days by mutableIntStateOf(3);var place by mutableStateOf("Зал");var health by mutableStateOf("")}
data class Measurement(val date:String,val values:Map<String,String>)
data class ProgressPhotos(val date:String,val front:String,val side:String,val back:String)
enum class Screen{WELCOME,GOAL,BASICS,EXP,DAYS,PLACE,HEALTH,HOME,PROFILE}
class MainActivity:ComponentActivity(){override fun onCreate(b:Bundle?){super.onCreate(b);setContent{App()}}}
@Composable fun App(){val c=LocalContext.current;val p=remember{loadProfile(c)};var s by remember{mutableStateOf(loadScreen(c))};var measurements by remember{mutableStateOf(loadMeasurements(c))};var photos by remember{mutableStateOf(loadPhotos(c))};LaunchedEffect(s,p.name,p.city,p.about,p.occupation,p.avatar,p.goal,p.age,p.height,p.weight,p.experience,p.days,p.place,p.health,measurements,photos){save(c,p,s,measurements,photos)};MaterialTheme(colorScheme=darkColorScheme(primary=Lime,background=Bg,surface=Card,onPrimary=androidx.compose.ui.graphics.Color.Black,onBackground=androidx.compose.ui.graphics.Color.White,onSurface=androidx.compose.ui.graphics.Color.White)){Surface(Modifier.fillMaxSize(),color=Bg){when(s){Screen.WELCOME->Page("Frost Fitness"){Text("Фростик поможет собрать персональную программу.");Go("Создать программу"){s=Screen.GOAL}};Screen.GOAL->Choice("Цель",listOf("Снизить вес","Набрать мышцы","Стать сильнее","Поддерживать форму"),p.goal,{p.goal=it}){s=Screen.BASICS};Screen.BASICS->Page("Основные данные"){Num("Возраст",p.age){p.age=it};Num("Рост, см",p.height){p.height=it};Num("Вес, кг",p.weight,true){p.weight=it};Go(enabled=p.age.isNotBlank()&&p.height.isNotBlank()&&p.weight.isNotBlank()){s=Screen.EXP}};Screen.EXP->Choice("Стаж тренировок",listOf("Начинающий","До 1 года","1–3 года","Более 3 лет"),p.experience,{p.experience=it}){s=Screen.DAYS};Screen.DAYS->Page("Тренировки в неделю"){Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){(2..5).forEach{n->FilterChip(p.days==n,{p.days=n},{Text("$n")})}};Go(){s=Screen.PLACE}};Screen.PLACE->Choice("Где тренируемся?",listOf("Зал","Дом: гантели","Дом: без оборудования"),p.place,{p.place=it}){s=Screen.HEALTH};Screen.HEALTH->Page("Здоровье"){Txt("Ограничения и противопоказания",p.health,4){p.health=it};Go("Создать программу",p.health.isNotBlank()){s=Screen.HOME}};Screen.HOME->Page("Сегодня","${p.goal} • ${p.days}× в неделю"){Info("Профиль и прогресс теперь сохраняются на устройстве.");Go("Мой профиль"){s=Screen.PROFILE}};Screen.PROFILE->ProfilePage(p,measurements,{measurements=measurements+it},photos,{photos=photos+it}){s=Screen.HOME}}}}}
@Composable fun ProfilePage(p:Profile,measurements:List<Measurement>,addMeasurement:(Measurement)->Unit,photos:List<ProgressPhotos>,addPhotos:(ProgressPhotos)->Unit,back:()->Unit){var tab by remember{mutableIntStateOf(0)};Page("Мой профиль"){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(6.dp)){listOf("Профиль","Замеры","Фото").forEachIndexed{i,t->FilterChip(tab==i,{tab=i},{Text(t)},Modifier.weight(1f))}};when(tab){0->ProfileFields(p);1->Measurements(measurements,addMeasurement);2->PhotoProgress(photos,addPhotos)};OutlinedButton(back,Modifier.fillMaxWidth()){Text("На главную")}}}
@Composable fun ProfileFields(p:Profile){val c=LocalContext.current;val avatarPick=rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()){u:Uri?->u?.let{runCatching{c.contentResolver.takePersistableUriPermission(it,android.content.Intent.FLAG_GRANT_READ_URI_PERMISSION)};p.avatar=it.toString()}};Box(Modifier.size(110.dp).clip(CircleShape).background(Card).align(Alignment.CenterHorizontally),contentAlignment=Alignment.Center){Text(if(p.avatar.isBlank())"Фото" else "✓ Фото",color=Lime)};OutlinedButton({avatarPick.launch(arrayOf("image/*"))},Modifier.fillMaxWidth()){Text(if(p.avatar.isBlank())"Выбрать фотографию" else "Изменить фотографию")};Txt("Имя",p.name){p.name=it};Txt("Город",p.city){p.city=it};Txt("Род деятельности",p.occupation){p.occupation=it};Txt("О себе",p.about,4){p.about=it};Num("Возраст",p.age){p.age=it};Num("Рост, см",p.height){p.height=it};Num("Вес, кг",p.weight,true){p.weight=it};Txt("Стаж тренировок",p.experience){p.experience=it};Txt("Цель",p.goal){p.goal=it};Txt("Место тренировок",p.place){p.place=it};Txt("Ограничения здоровья",p.health,3){p.health=it};Info("Изменения сохраняются автоматически.")}
@Composable fun Measurements(items:List<Measurement>,add:(Measurement)->Unit){val labels=listOf("Вес","Шея","Плечи","Грудь","Талия","Живот","Бёдра","Бицепс левый","Бицепс правый","Предплечье левое","Предплечье правое","Бедро левое","Бедро правое","Икра левая","Икра правая");val values=remember{mutableStateMapOf<String,String>()};Text("Новый замер",fontSize=20.sp,fontWeight=FontWeight.Bold);labels.forEach{l->Num(if(l=="Вес")"$l, кг" else "$l, см",values[l]?:"",true){values[l]=it}};Go("Сохранить замер",values.values.any{it.isNotBlank()}){add(Measurement(LocalDate.now().toString(),values.toMap()));values.clear()};if(items.isNotEmpty()){Text("История",fontSize=20.sp,fontWeight=FontWeight.Bold);items.asReversed().forEach{m->Info(m.date+"\n"+m.values.filterValues{it.isNotBlank()}.entries.joinToString(" • "){"${it.key}: ${it.value}"})}}}
@Composable fun PhotoProgress(items:List<ProgressPhotos>,add:(ProgressPhotos)->Unit){val c=LocalContext.current;var front by remember{mutableStateOf("")};var side by remember{mutableStateOf("")};var back by remember{mutableStateOf("")};fun persist(u:Uri?):String{if(u==null)return "";runCatching{c.contentResolver.takePersistableUriPermission(u,android.content.Intent.FLAG_GRANT_READ_URI_PERMISSION)};return u.toString()};val f=rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()){front=persist(it)};val s=rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()){side=persist(it)};val b=rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()){back=persist(it)};Info("Для будущего ИИ-сравнения делай фотографии в одинаковом освещении, с одинакового расстояния и в одинаковой позе.");OutlinedButton({f.launch(arrayOf("image/*"))},Modifier.fillMaxWidth()){Text(if(front.isBlank())"Фото спереди" else "✓ Спереди")};OutlinedButton({s.launch(arrayOf("image/*"))},Modifier.fillMaxWidth()){Text(if(side.isBlank())"Фото сбоку" else "✓ Сбоку")};OutlinedButton({b.launch(arrayOf("image/*"))},Modifier.fillMaxWidth()){Text(if(back.isBlank())"Фото сзади" else "✓ Сзади")};Go("Сохранить фото прогресса",front.isNotBlank()||side.isNotBlank()||back.isNotBlank()){add(ProgressPhotos(LocalDate.now().toString(),front,side,back));front="";side="";back=""};if(items.isNotEmpty()){Text("История фото",fontSize=20.sp,fontWeight=FontWeight.Bold);items.asReversed().forEach{Info("${it.date} • спереди ${if(it.front.isBlank())"—" else "✓"} • сбоку ${if(it.side.isBlank())"—" else "✓"} • сзади ${if(it.back.isBlank())"—" else "✓"}")}};Info("ИИ-анализ будет подключён отдельным обновлением. Фотографии сейчас сохраняются для истории прогресса.")}
@Composable fun Page(title:String,sub:String="",body:@Composable ColumnScope.()->Unit){Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).navigationBarsPadding().padding(22.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){Text("FF",color=Lime,fontSize=30.sp,fontWeight=FontWeight.Black);Text(title,fontSize=30.sp,fontWeight=FontWeight.Bold);if(sub.isNotBlank())Text(sub,color=Muted);body();Spacer(Modifier.height(20.dp))}}
@Composable fun Info(t:String){Text(t,Modifier.fillMaxWidth().background(Card,RoundedCornerShape(18.dp)).padding(16.dp))}
@Composable fun Go(text:String="Продолжить",enabled:Boolean=true,click:()->Unit){Button(click,Modifier.fillMaxWidth().height(54.dp),enabled=enabled,colors=ButtonDefaults.buttonColors(containerColor=Lime,contentColor=androidx.compose.ui.graphics.Color.Black)){Text(text,fontWeight=FontWeight.Bold)}}
@Composable fun Txt(label:String,value:String,lines:Int=1,set:(String)->Unit){OutlinedTextField(value,set,label={Text(label)},singleLine=lines==1,minLines=lines,modifier=Modifier.fillMaxWidth())}
@Composable fun Num(label:String,value:String,decimal:Boolean=false,set:(String)->Unit){OutlinedTextField(value,{raw->val x=raw.replace(',','.');set(if(decimal)x.filterIndexed{i,ch->ch.isDigit()||(ch=='.'&&i>0&&x.take(i).none{it=='.'})}else x.filter{it.isDigit()})},label={Text(label)},singleLine=true,keyboardOptions=KeyboardOptions(keyboardType=if(decimal)KeyboardType.Decimal else KeyboardType.Number),modifier=Modifier.fillMaxWidth())}
@Composable fun Choice(title:String,items:List<String>,initial:String,set:(String)->Unit,next:()->Unit){var v by remember(title){mutableStateOf(initial)};Page(title){items.forEach{FilterChip(v==it,{v=it;set(it)},{Text(it)},Modifier.fillMaxWidth())};Go(enabled=v.isNotBlank(),click=next)}}
fun prefs(c:android.content.Context)=c.getSharedPreferences("frost_fitness",android.content.Context.MODE_PRIVATE)
fun loadProfile(c:android.content.Context)=Profile().apply{val x=prefs(c);name=x.getString("name","")!!;city=x.getString("city","")!!;about=x.getString("about","")!!;occupation=x.getString("occupation","")!!;avatar=x.getString("avatar","")!!;goal=x.getString("goal","")!!;age=x.getString("age","")!!;height=x.getString("height","")!!;weight=x.getString("weight","")!!;experience=x.getString("experience","")!!;days=x.getInt("days",3);place=x.getString("place","Зал")!!;health=x.getString("health","")!!}
fun loadScreen(c:android.content.Context)=runCatching{Screen.valueOf(prefs(c).getString("screen","WELCOME")!!)}.getOrDefault(Screen.WELCOME)
fun esc(s:String)=android.util.Base64.encodeToString(s.toByteArray(),android.util.Base64.NO_WRAP);fun unesc(s:String)=runCatching{String(android.util.Base64.decode(s,android.util.Base64.NO_WRAP))}.getOrDefault("")
fun save(c:android.content.Context,p:Profile,s:Screen,m:List<Measurement>,ph:List<ProgressPhotos>){prefs(c).edit().putString("name",p.name).putString("city",p.city).putString("about",p.about).putString("occupation",p.occupation).putString("avatar",p.avatar).putString("goal",p.goal).putString("age",p.age).putString("height",p.height).putString("weight",p.weight).putString("experience",p.experience).putInt("days",p.days).putString("place",p.place).putString("health",p.health).putString("screen",s.name).putString("measurements",m.joinToString(";"){esc(it.date)+","+esc(it.values.entries.joinToString("|"){e->e.key+"="+e.value})}).putString("photos",ph.joinToString(";"){listOf(it.date,it.front,it.side,it.back).joinToString(","){v->esc(v)}}).apply()}
fun loadMeasurements(c:android.content.Context):List<Measurement>{val raw=prefs(c).getString("measurements","")?:"";if(raw.isBlank())return emptyList();return raw.split(';').mapNotNull{r->val q=r.split(',',limit=2);if(q.size<2)null else Measurement(unesc(q[0]),unesc(q[1]).split('|').mapNotNull{e->val z=e.split('=',limit=2);if(z.size==2)z[0] to z[1] else null}.toMap())}}
fun loadPhotos(c:android.content.Context):List<ProgressPhotos>{val raw=prefs(c).getString("photos","")?:"";if(raw.isBlank())return emptyList();return raw.split(';').mapNotNull{r->val q=r.split(',');if(q.size==4)ProgressPhotos(unesc(q[0]),unesc(q[1]),unesc(q[2]),unesc(q[3]))else null}}
