package com.frostfitness.app

import android.content.Context
import android.content.Intent
import android.net.Uri
import android.os.Bundle
import android.os.Handler
import android.os.Looper
import android.widget.ImageView
import androidx.activity.ComponentActivity
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.compose.setContent
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.viewinterop.AndroidView
import java.net.HttpURLConnection
import java.net.URL
import java.time.Instant
import java.time.ZoneId
import java.time.format.DateTimeFormatter

private val Accent=Color(0xFF9BE52A);private val LightBg=Color(0xFFF2F2F7);private val LightCard=Color.White;private val LightInk=Color(0xFF111111);private val LightSub=Color(0xFF6E6E73);private val LightLine=Color(0xFFE5E5EA);private val DarkBg=Color.Black;private val DarkCard=Color(0xFF1C1C1E);private val DarkInk=Color(0xFFF5F5F7);private val DarkSub=Color(0xFF98989D);private val DarkLine=Color(0xFF38383A)
private var UiBg=LightBg;private var UiCard=LightCard;private var UiInk=LightInk;private var UiSub=LightSub;private var UiLine=LightLine
enum class ThemeMode{SYSTEM,LIGHT,DARK};enum class Screen{WELCOME,THEME,BASICS,DETAILS,GOAL,EXP,DAYS,PLACE,EQUIPMENT,HEALTH,HOME,PROFILE}
class Profile{var name by mutableStateOf("");var city by mutableStateOf("");var about by mutableStateOf("");var occupation by mutableStateOf("");var avatar by mutableStateOf("");var goal by mutableStateOf("");var age by mutableStateOf("");var height by mutableStateOf("");var weight by mutableStateOf("");var experience by mutableStateOf("");var days by mutableIntStateOf(3);var place by mutableStateOf("Зал");var equipment by mutableStateOf("");var health by mutableStateOf("")}
data class Measurement(val date:String,val values:Map<String,String>);data class ProgressPhotos(val date:String,val front:String,val side:String,val back:String)
class MainActivity:ComponentActivity(){override fun onCreate(b:Bundle?){super.onCreate(b);setContent{App()}}}
@Composable fun App(){val c=LocalContext.current;val p=remember{loadProfile(c)};var screen by remember{mutableStateOf(loadScreen(c))};var mode by remember{mutableStateOf(loadTheme(c))};var ms by remember{mutableStateOf(loadMeasurements(c))};var photos by remember{mutableStateOf(loadPhotos(c))};val dark=when(mode){ThemeMode.SYSTEM->isSystemInDarkTheme();ThemeMode.LIGHT->false;ThemeMode.DARK->true};UiBg=if(dark)DarkBg else LightBg;UiCard=if(dark)DarkCard else LightCard;UiInk=if(dark)DarkInk else LightInk;UiSub=if(dark)DarkSub else LightSub;UiLine=if(dark)DarkLine else LightLine;LaunchedEffect(screen,mode,p.name,p.city,p.about,p.occupation,p.avatar,p.goal,p.age,p.height,p.weight,p.experience,p.days,p.place,p.equipment,p.health,ms,photos){save(c,p,screen,mode,ms,photos)};MaterialTheme(colorScheme=if(dark)darkColorScheme(background=UiBg,surface=UiCard,onBackground=UiInk,onSurface=UiInk) else lightColorScheme(background=UiBg,surface=UiCard,onBackground=UiInk,onSurface=UiInk)){Surface(Modifier.fillMaxSize(),color=UiBg){when(screen){Screen.WELCOME->Welcome{screen=Screen.THEME};Screen.THEME->ThemePick(mode,{mode=it}){screen=Screen.BASICS};Screen.BASICS->Basics(p){screen=Screen.DETAILS};Screen.DETAILS->Details(p){screen=Screen.GOAL};Screen.GOAL->Choice("Какая у тебя цель?",listOf("Снизить вес","Набрать мышцы","Стать сильнее","Поддерживать форму"),p.goal,{p.goal=it}){screen=Screen.EXP};Screen.EXP->Choice("Опыт тренировок",listOf("Начинающий","До 1 года","1–3 года","Более 3 лет"),p.experience,{p.experience=it}){screen=Screen.DAYS};Screen.DAYS->Page("Ритм тренировок","Сколько раз в неделю тебе удобно заниматься?"){Segment((2..5).map{it.toString()},p.days.toString()){p.days=it.toInt()};Primary(){screen=Screen.PLACE}};Screen.PLACE->PlaceScreen(p){screen=if(p.place=="Дом")Screen.EQUIPMENT else Screen.HEALTH};Screen.EQUIPMENT->EquipmentScreen(p){screen=Screen.HEALTH};Screen.HEALTH->HealthScreen(p){screen=Screen.HOME};Screen.HOME->Home(p){screen=Screen.PROFILE};Screen.PROFILE->ProfilePage(p,mode,{mode=it},ms,{ms=ms+it},photos,{photos=photos+it}){screen=Screen.HOME}}}}}
@Composable fun Welcome(next:()->Unit){Page("Добро пожаловать\nв Frost Fitness","Твой персональный путь к форме начинается здесь."){FrostikHero();Text("Я Фростик. Помогу настроить тренировки и следить за прогрессом.",fontSize=18.sp,fontWeight=FontWeight.SemiBold,lineHeight=25.sp);Primary("Заполнить анкету",click=next)}}
@Composable fun FrostikHero(){Box(Modifier.fillMaxWidth().height(260.dp).background(UiCard,RoundedCornerShape(32.dp)),contentAlignment=Alignment.Center){Column(horizontalAlignment=Alignment.CenterHorizontally){Text("🏋️  🧔🏻‍♂️  🏋️",fontSize=52.sp);Spacer(Modifier.height(14.dp));Text("ФРОСТИК",fontWeight=FontWeight.Bold,letterSpacing=2.sp,color=UiSub)}}}
@Composable fun ThemePick(mode:ThemeMode,set:(ThemeMode)->Unit,next:()->Unit){Page("Выбери оформление","По умолчанию используется тема телефона."){ThemeOption("Светлая тема",mode==ThemeMode.LIGHT){set(ThemeMode.LIGHT)};ThemeOption("Как на телефоне",mode==ThemeMode.SYSTEM){set(ThemeMode.SYSTEM)};ThemeOption("Тёмная тема",mode==ThemeMode.DARK){set(ThemeMode.DARK)};Primary("Продолжить",click=next)}}
@Composable fun ThemeOption(t:String,on:Boolean,click:()->Unit){Button(click,Modifier.fillMaxWidth().height(64.dp),shape=RoundedCornerShape(18.dp),colors=ButtonDefaults.buttonColors(containerColor=UiCard,contentColor=UiInk)){Text(t,Modifier.weight(1f));Text(if(on)"●" else "○",fontSize=24.sp,color=if(on)Accent else UiSub)}}
@Composable fun Basics(p:Profile,next:()->Unit){val c=LocalContext.current;val pick=rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()){u:Uri?->u?.let{runCatching{c.contentResolver.takePersistableUriPermission(it,Intent.FLAG_GRANT_READ_URI_PERMISSION)};p.avatar=it.toString()}};Page("Расскажи о себе","Начнём с основных данных."){Column(Modifier.fillMaxWidth(),horizontalAlignment=Alignment.CenterHorizontally){Avatar(p.avatar);TextButton({pick.launch(arrayOf("image/*"))}){Text(if(p.avatar.isBlank())"Добавить фотографию" else "Изменить фотографию")}};Section("Основные данные"){Field("Имя",p.name){p.name=it};Field("Город",p.city){p.city=it};FieldNum("Возраст",p.age){p.age=it};FieldNum("Рост, см",p.height){p.height=it};FieldNum("Вес, кг",p.weight,true){p.weight=it}};Primary("Продолжить",p.name.isNotBlank()&&p.city.isNotBlank()&&p.age.isNotBlank()&&p.height.isNotBlank()&&p.weight.isNotBlank(),next)}}
@Composable fun Avatar(uri:String){Box(Modifier.size(112.dp).clip(CircleShape).background(UiLine),contentAlignment=Alignment.Center){if(uri.isBlank())Text("Фото",color=UiSub)else AndroidView(factory={ImageView(it).apply{scaleType=ImageView.ScaleType.CENTER_CROP}},update={it.setImageURI(Uri.parse(uri))},modifier=Modifier.fillMaxSize())}}
@Composable fun Details(p:Profile,next:()->Unit){Page("Ещё немного о тебе"){Section("О себе"){Field("Род деятельности",p.occupation){p.occupation=it};Field("О себе",p.about,4){p.about=it}};Primary("Продолжить",p.occupation.isNotBlank(),next)}}
@Composable fun PlaceScreen(p:Profile,next:()->Unit){var choice by remember{mutableStateOf(if(p.place in listOf("Зал","Дом"))p.place else "")};Page("Где тренируемся?","Выбери основное место тренировок."){SelectCard("Зал",choice=="Зал"){choice="Зал";p.place="Зал";p.equipment=""};SelectCard("Дом",choice=="Дом"){choice="Дом";p.place="Дом"};Primary(enabled=choice.isNotBlank(),click=next)}}
@Composable fun EquipmentScreen(p:Profile,next:()->Unit){val opts=listOf("Гантели","Штанга и блины","Гири","Резинки","Турник","Скамья","Коврик","Без оборудования");val selected=remember{mutableStateListOf<String>().apply{addAll(p.equipment.split('|').filter{it.isNotBlank()})}};Page("Что есть дома?","Можно выбрать несколько вариантов."){opts.forEach{o->SelectCard(o,o in selected){if(o=="Без оборудования"){selected.clear();selected.add(o)}else{selected.remove("Без оборудования");if(o in selected)selected.remove(o)else selected.add(o)};p.equipment=selected.joinToString("|")}};Primary(enabled=selected.isNotEmpty(),click=next)}}
@Composable fun HealthScreen(p:Profile,next:()->Unit){var none by remember{mutableStateOf(p.health=="Нет противопоказаний")};Page("Здоровье","Укажи ограничения, которые важно учитывать."){SelectCard("Нет противопоказаний",none){none=true;p.health="Нет противопоказаний"};Field("Ограничения и противопоказания",if(none)"" else p.health,4){none=false;p.health=it};Primary("Завершить анкету",p.health.isNotBlank(),next)}}
@Composable fun Home(p:Profile,profile:()->Unit){Page(if(p.name.isBlank())"Сегодня" else "Привет, ${p.name}","${p.goal} · ${p.days} тренировки в неделю"){Hero("Ф","Фростик рядом. Сегодня двигаемся по твоему плану.");CardBlock{Text("Сегодня",color=UiSub);Text("Тренировка всего тела",fontSize=22.sp,fontWeight=FontWeight.Bold);Text("45 мин · 6 упражнений",color=UiSub);Primary("Начать тренировку"){} };SecondaryButton("Мой профиль и замеры",profile)}}
@Composable fun ProfilePage(p:Profile,mode:ThemeMode,setMode:(ThemeMode)->Unit,ms:List<Measurement>,addM:(Measurement)->Unit,ph:List<ProgressPhotos>,addP:(ProgressPhotos)->Unit,back:()->Unit){var tab by remember{mutableIntStateOf(0)};Page("Профиль",p.name){Segment(listOf("Профиль","Замеры","Фото"),listOf("Профиль","Замеры","Фото")[tab]){tab=listOf("Профиль","Замеры","Фото").indexOf(it)};when(tab){0->ProfileFields(p,mode,setMode);1->Measurements(ms,addM);2->PhotoProgress(ph,addP)};SecondaryButton("Готово",back)}}
@Composable fun ProfileFields(p:Profile,mode:ThemeMode,setMode:(ThemeMode)->Unit){Section("Основное"){Field("Имя",p.name){p.name=it};Field("Город",p.city){p.city=it};Field("Род деятельности",p.occupation){p.occupation=it};Field("О себе",p.about,3){p.about=it}};Section("Физические данные"){FieldNum("Возраст",p.age){p.age=it};FieldNum("Рост, см",p.height){p.height=it};FieldNum("Вес, кг",p.weight,true){p.weight=it}};Section("Тренировки"){Field("Стаж",p.experience){p.experience=it};Field("Цель",p.goal){p.goal=it};Field("Место",p.place){p.place=it};if(p.place=="Дом")Field("Оборудование",p.equipment){p.equipment=it};Field("Здоровье",p.health){p.health=it}};Text("Оформление",fontSize=20.sp,fontWeight=FontWeight.Bold);Segment(listOf("Светлая","Система","Тёмная"),when(mode){ThemeMode.LIGHT->"Светлая";ThemeMode.SYSTEM->"Система";ThemeMode.DARK->"Тёмная"}){setMode(when(it){"Светлая"->ThemeMode.LIGHT;"Тёмная"->ThemeMode.DARK;else->ThemeMode.SYSTEM})}}
@Composable fun Measurements(items:List<Measurement>,add:(Measurement)->Unit){var adding by remember{mutableStateOf(false)};var opened by remember{mutableStateOf<Measurement?>(null)};val labels=listOf("Вес","Шея","Плечи","Грудь","Талия","Живот","Бёдра","Бицепс левый","Бицепс правый","Предплечье левое","Предплечье правое","Бедро левое","Бедро правое","Икра левая","Икра правая");val v=remember{mutableStateMapOf<String,String>()};var status by remember{mutableStateOf("")};when{opened!=null->{Text(opened!!.date,fontSize=24.sp,fontWeight=FontWeight.Bold);opened!!.values.filterValues{it.isNotBlank()}.forEach{(k,x)->CardBlock{Text(k,color=UiSub);Text(x,fontSize=20.sp,fontWeight=FontWeight.SemiBold)}};SecondaryButton("Назад"){opened=null}};adding->{Text("Новый замер",fontSize=24.sp,fontWeight=FontWeight.Bold);Section("Показатели"){labels.forEach{l->FieldNum(if(l=="Вес")"$l, кг" else "$l, см",v[l]?:"",true){v[l]=it}}};if(status.isNotBlank())Text(status,color=UiSub);Primary("Сохранить замер",v.values.any{it.isNotBlank()}){status="Получаю дату из интернета…";networkDate{date->if(date==null)status="Не удалось получить дату. Проверь интернет." else{add(Measurement(date,v.toMap()));v.clear();status="";adding=false}}};SecondaryButton("Отмена"){adding=false}};else->{Primary("＋ Добавить замеры"){adding=true};if(items.isEmpty())Text("Пока нет сохранённых замеров.",color=UiSub)else{Text("История",fontSize=22.sp,fontWeight=FontWeight.Bold);items.asReversed().forEach{m->CardBlock{Row(Modifier.fillMaxWidth().clickable{opened=m}.padding(vertical=6.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(prettyDate(m.date),fontSize=17.sp,fontWeight=FontWeight.SemiBold);Text("Посмотреть замер",color=UiSub,fontSize=13.sp)};Text("›",fontSize=28.sp,color=UiSub)}}}}}}
fun networkDate(done:(String?)->Unit){Thread{val result=runCatching{val con=(URL("https://www.google.com/generate_204").openConnection() as HttpURLConnection);con.requestMethod="HEAD";con.connectTimeout=5000;con.readTimeout=5000;con.connect();val ms=con.date;con.disconnect();if(ms<=0)error("no date");Instant.ofEpochMilli(ms).atZone(ZoneId.systemDefault()).toLocalDate().toString()}.getOrNull();Handler(Looper.getMainLooper()).post{done(result)}}.start()}
fun prettyDate(s:String)=runCatching{java.time.LocalDate.parse(s).format(DateTimeFormatter.ofPattern("dd.MM.yyyy"))}.getOrDefault(s)
@Composable fun PhotoProgress(items:List<ProgressPhotos>,add:(ProgressPhotos)->Unit){val c=LocalContext.current;var f0 by remember{mutableStateOf("")};var s0 by remember{mutableStateOf("")};var b0 by remember{mutableStateOf("")};fun keep(u:Uri?):String{if(u==null)return "";runCatching{c.contentResolver.takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION)};return u.toString()};val f=rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()){f0=keep(it)};val s=rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()){s0=keep(it)};val b=rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()){b0=keep(it)};Hero("AI","Фото прогресса: одинаковый свет, расстояние и поза.");PhotoRow("Спереди",f0.isNotBlank()){f.launch(arrayOf("image/*"))};PhotoRow("Сбоку",s0.isNotBlank()){s.launch(arrayOf("image/*"))};PhotoRow("Сзади",b0.isNotBlank()){b.launch(arrayOf("image/*"))};Primary("Сохранить серию",f0.isNotBlank()||s0.isNotBlank()||b0.isNotBlank()){add(ProgressPhotos(java.time.LocalDate.now().toString(),f0,s0,b0));f0="";s0="";b0=""};items.asReversed().forEach{CardBlock{Text(it.date)}}}
@Composable fun Page(title:String,sub:String="",body:@Composable ColumnScope.()->Unit){Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).statusBarsPadding().navigationBarsPadding().imePadding().padding(horizontal=20.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){Spacer(Modifier.height(14.dp));Text("FROST FITNESS",fontSize=12.sp,fontWeight=FontWeight.Bold,color=UiSub);Text(title,fontSize=34.sp,lineHeight=42.sp,fontWeight=FontWeight.Bold);if(sub.isNotBlank())Text(sub,color=UiSub,fontSize=16.sp,lineHeight=22.sp);body();Spacer(Modifier.height(36.dp))}}
@Composable fun SelectCard(t:String,on:Boolean,click:()->Unit){Button(click,Modifier.fillMaxWidth().height(58.dp),shape=RoundedCornerShape(16.dp),colors=ButtonDefaults.buttonColors(containerColor=UiCard,contentColor=UiInk)){Text(t,Modifier.weight(1f));Text(if(on)"✓" else "",color=Accent,fontWeight=FontWeight.Bold)}}
@Composable fun Hero(mark:String,text:String){Row(Modifier.fillMaxWidth().background(UiCard,RoundedCornerShape(24.dp)).padding(18.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(52.dp).clip(CircleShape).background(Accent),contentAlignment=Alignment.Center){Text(mark,fontWeight=FontWeight.Bold,color=Color.Black)};Spacer(Modifier.width(14.dp));Text(text,Modifier.weight(1f),fontSize=17.sp,fontWeight=FontWeight.SemiBold)}}
@Composable fun CardBlock(body:@Composable ColumnScope.()->Unit){Column(Modifier.fillMaxWidth().background(UiCard,RoundedCornerShape(20.dp)).padding(16.dp),verticalArrangement=Arrangement.spacedBy(5.dp),content=body)}
@Composable fun Section(title:String,body:@Composable ColumnScope.()->Unit){Text(title.uppercase(),fontSize=12.sp,color=UiSub);Column(Modifier.fillMaxWidth().background(UiCard,RoundedCornerShape(18.dp)).padding(12.dp),verticalArrangement=Arrangement.spacedBy(4.dp),content=body)}
@Composable fun Primary(text:String="Продолжить",enabled:Boolean=true,click:()->Unit){Button(click,Modifier.fillMaxWidth().height(54.dp),enabled=enabled,shape=RoundedCornerShape(16.dp),colors=ButtonDefaults.buttonColors(containerColor=Accent,contentColor=Color.Black)){Text(text,fontWeight=FontWeight.Bold)}}
@Composable fun SecondaryButton(text:String,click:()->Unit){OutlinedButton(click,Modifier.fillMaxWidth().height(52.dp),shape=RoundedCornerShape(16.dp)){Text(text,color=UiInk,fontWeight=FontWeight.SemiBold)}}
@Composable fun Field(label:String,value:String,lines:Int=1,set:(String)->Unit){OutlinedTextField(value,set,label={Text(label)},singleLine=lines==1,minLines=lines,shape=RoundedCornerShape(14.dp),colors=OutlinedTextFieldDefaults.colors(unfocusedBorderColor=UiLine,focusedBorderColor=Accent),modifier=Modifier.fillMaxWidth())}
@Composable fun FieldNum(label:String,value:String,decimal:Boolean=false,set:(String)->Unit){OutlinedTextField(value,{raw->val x=raw.replace(',','.');set(if(decimal)x.filterIndexed{i,ch->ch.isDigit()||(ch=='.'&&i>0&&x.take(i).none{it=='.'})}else x.filter{it.isDigit()})},label={Text(label)},singleLine=true,keyboardOptions=KeyboardOptions(keyboardType=if(decimal)KeyboardType.Decimal else KeyboardType.Number),shape=RoundedCornerShape(14.dp),modifier=Modifier.fillMaxWidth())}
@Composable fun Segment(items:List<String>,selected:String,set:(String)->Unit){Row(Modifier.fillMaxWidth().background(UiLine,RoundedCornerShape(12.dp)).padding(3.dp),horizontalArrangement=Arrangement.spacedBy(3.dp)){items.forEach{item->Button({set(item)},Modifier.weight(1f).height(40.dp),shape=RoundedCornerShape(10.dp),contentPadding=PaddingValues(2.dp),colors=ButtonDefaults.buttonColors(containerColor=if(item==selected)UiCard else Color.Transparent,contentColor=UiInk)){Text(item,fontSize=12.sp)}}}}
@Composable fun Choice(title:String,items:List<String>,initial:String,set:(String)->Unit,next:()->Unit){var v by remember(title){mutableStateOf(initial)};Page(title,"Выбери один вариант"){items.forEach{SelectCard(it,v==it){v=it;set(it)}};Primary(enabled=v.isNotBlank(),click=next)}}
@Composable fun PhotoRow(t:String,done:Boolean,click:()->Unit){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Text(t,Modifier.weight(1f));TextButton(click){Text(if(done)"Выбрано ✓" else "Выбрать")}}}
fun prefs(c:Context)=c.getSharedPreferences("frost_fitness",Context.MODE_PRIVATE)
fun loadProfile(c:Context)=Profile().apply{val x=prefs(c);name=x.getString("name","")!!;city=x.getString("city","")!!;about=x.getString("about","")!!;occupation=x.getString("occupation","")!!;avatar=x.getString("avatar","")!!;goal=x.getString("goal","")!!;age=x.getString("age","")!!;height=x.getString("height","")!!;weight=x.getString("weight","")!!;experience=x.getString("experience","")!!;days=x.getInt("days",3);place=x.getString("place","Зал")!!.let{if(it.startsWith("Дом"))"Дом" else it};equipment=x.getString("equipment","")!!;health=x.getString("health","")!!}
fun loadScreen(c:Context)=runCatching{Screen.valueOf(prefs(c).getString("screen","WELCOME")!!)}.getOrDefault(Screen.WELCOME);fun loadTheme(c:Context)=runCatching{ThemeMode.valueOf(prefs(c).getString("theme","SYSTEM")!!)}.getOrDefault(ThemeMode.SYSTEM)
fun esc(s:String)=android.util.Base64.encodeToString(s.toByteArray(),android.util.Base64.NO_WRAP);fun unesc(s:String)=runCatching{String(android.util.Base64.decode(s,android.util.Base64.NO_WRAP))}.getOrDefault("")
fun save(c:Context,p:Profile,s:Screen,t:ThemeMode,m:List<Measurement>,ph:List<ProgressPhotos>){prefs(c).edit().putString("name",p.name).putString("city",p.city).putString("about",p.about).putString("occupation",p.occupation).putString("avatar",p.avatar).putString("goal",p.goal).putString("age",p.age).putString("height",p.height).putString("weight",p.weight).putString("experience",p.experience).putInt("days",p.days).putString("place",p.place).putString("equipment",p.equipment).putString("health",p.health).putString("screen",s.name).putString("theme",t.name).putString("measurements",m.joinToString(";"){esc(it.date)+","+esc(it.values.entries.joinToString("|"){e->e.key+"="+e.value})}).putString("photos",ph.joinToString(";"){listOf(it.date,it.front,it.side,it.back).joinToString(","){v->esc(v)}}).apply()}
fun loadMeasurements(c:Context):List<Measurement>{val raw=prefs(c).getString("measurements","")?:"";if(raw.isBlank())return emptyList();return raw.split(';').mapNotNull{r->val q=r.split(',',limit=2);if(q.size<2)null else Measurement(unesc(q[0]),unesc(q[1]).split('|').mapNotNull{e->val z=e.split('=',limit=2);if(z.size==2)z[0] to z[1] else null}.toMap())}}
fun loadPhotos(c:Context):List<ProgressPhotos>{val raw=prefs(c).getString("photos","")?:"";if(raw.isBlank())return emptyList();return raw.split(';').mapNotNull{r->val q=r.split(',');if(q.size==4)ProgressPhotos(unesc(q[0]),unesc(q[1]),unesc(q[2]),unesc(q[3]))else null}}
